/**
 * Canonical application route paths (spec §9).
 * Single source of truth shared by the frontend router and any
 * server-side link generation — never hand-type a route path elsewhere.
 */
export const ROUTES = {
  home: '/',
  tenders: '/tenders',
  tenderDetail: (id: string) => `/tenders/${id}`,
  opportunities: '/opportunities',
  watchlist: '/watchlist',
  bids: '/bids',
  bidDetail: (id: string) => `/bids/${id}`,
  bidStrategy: (id: string) => `/bids/${id}/strategy`,
  bidCompliance: (id: string) => `/bids/${id}/compliance`,
  bidDocuments: (id: string) => `/bids/${id}/documents`,
  agency: '/agency',
  agencyCapabilities: '/agency/capabilities',
  agencyPortfolio: '/agency/portfolio',
  agencyTeam: '/agency/team',
  agencyDocuments: '/agency/documents',
  analytics: '/analytics',
  outcomes: '/outcomes',
  competitors: '/competitors',
  intelligence: '/intelligence',
  intelligenceBenchmarks: '/intelligence/benchmarks',
  dataQuality: '/data-quality',
  notifications: '/notifications',
  opsHealth: '/ops',
  sources: '/sources',
  sourceDetail: (id: string) => `/sources/${id}`,
  settings: '/settings',
  settingsAuditLogs: '/settings/audit-logs',
  login: '/login',
} as const

export const ROUTE_PATTERNS = {
  home: '/',
  tenders: '/tenders',
  tenderDetail: '/tenders/:id',
  opportunities: '/opportunities',
  watchlist: '/watchlist',
  bids: '/bids',
  bidDetail: '/bids/:id',
  bidStrategy: '/bids/:id/strategy',
  bidCompliance: '/bids/:id/compliance',
  bidDocuments: '/bids/:id/documents',
  agency: '/agency',
  agencyCapabilities: '/agency/capabilities',
  agencyPortfolio: '/agency/portfolio',
  agencyTeam: '/agency/team',
  agencyDocuments: '/agency/documents',
  analytics: '/analytics',
  outcomes: '/outcomes',
  competitors: '/competitors',
  intelligence: '/intelligence',
  intelligenceBenchmarks: '/intelligence/benchmarks',
  dataQuality: '/data-quality',
  notifications: '/notifications',
  opsHealth: '/ops',
  sources: '/sources',
  sourceDetail: '/sources/:id',
  settings: '/settings',
  settingsAuditLogs: '/settings/audit-logs',
  login: '/login',
} as const
